platform :ios, '11.0'
inhibit_all_warnings!

target 'ReactNativeApp' do
  use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',   # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTWebSocket', # needed for debugging
    'ART',
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTText',
    'RCTLinkingIOS',
    'RCTActionSheet',
    'RCTBlob',
    'RCTGeolocation',
    'RCTSettings',
    'RCTVibration'
  ]
  pod "yoga", :path => '../node_modules/react-native/ReactCommon/yoga'
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs'

  target 'ReactNativeAppTests' do
    inherit! :search_paths
  end

end

def fix_cplusplus_header_compiler_error
  # RCTSurfaceSizeMeasureMode
  # https://github.com/facebook/yoga/issues/711
  filepath = '../node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h'
  contents = []
  file = File.open(filepath, 'r')
  file.each_line do | line |
    contents << line
  end
  file.close
  if contents[32].include? "&"
    contents.insert(26, "#ifdef __cplusplus")
    contents[36] = "#endif"
    file = File.open(filepath, 'w') do |f|
      f.puts(contents)
    end
  end
end

 post_install do |installer|
  
  puts 'Patching React Native'
  `sed -i '' 's/(^)())block/(^)(void))block/' ../node_modules/react-native/Libraries/Image/RCTImageStoreManager.h`

  # https://github.com/facebook/react-native/issues/13198
  `sed -i '' 's|<RCTAnimation/RCTValueAnimatedNode.h>|"RCTValueAnimatedNode.h"|' ../node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h`

  # https://github.com/facebook/react-native/issues/16039
  `sed -i '' 's|fishhook/fishhook.h|React/fishhook.h|' ../node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m`

  # https://github.com/facebook/yoga/issues/711
  # https://github.com/facebook/react-native/pull/17764
  `sed -i '' '/Utils.h/d' "./Pods/Target Support Files/yoga/yoga-umbrella.h"`
  `sed -i '' '/YGNode.h/d' "./Pods/Target Support Files/yoga/yoga-umbrella.h"`
  `sed -i '' '/YGNodePrint.h/d' "./Pods/Target Support Files/yoga/yoga-umbrella.h"`
  `sed -i '' '/Yoga-internal.h/d' "./Pods/Target Support Files/yoga/yoga-umbrella.h"`

  fix_cplusplus_header_compiler_error

 end
